### ISSUE TITLE
有几个功能缺失，希望在下个版本可以增加

### ISSUE THREAD

**Issue by linhaikun2019** [celaraze/cat#110]
1.首先是资产列表里的这些固定字段太固定了，建议加一个自定义字段的功能，让用户自由新增或删除字段，比如我可能不想要规格，想要个位置啊，或者加个备注啊，等等诸如此类。。。。
2.希望资产照片可以支持多个，现在只能上传一个，受限制很大
目前发现这2个功能缺陷，烦请作者研究一下，能在下个版本更新就最好了，谢谢！

**Comment by linhaikun2019** [comment]
3.日志功能还不太完善，现在只有导入日志，可以加些系统日志，操作日志等等

**Comment by celaraze** [comment]
1，不会做自定义字段，我在此说明过：[常见问题](https://github.com/celaraze/cat/wiki/%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98) 。备注已经实装，位置有后续的区域管理实现。
2，暂时不会提供多图，请从实际管理角度考虑优化，资产管理不是多媒体管理。
3，计划之内。
