### ISSUE TITLE
资产详情里面缺少说明内容

### ISSUE THREAD

**Issue by linhaikun2019** [celaraze/cat#113]
### 先确认

***1，是否使用最新版本，可以使用 `php artisan cat:version` 获取当前版本。***
答：是

***2，是否有跳过应用处理逻辑，而自行修改数据库结构、数据等操作。***
答：否

***3，是否有二次开发操作。***
答：否

### 再描述

***1，你的 PHP 、 MySQL 版本号。***
答：

***2，当前使用的 CAT 版本号。***
答：

***3，你遇到了什么问题，尽量描述清楚，尤其是附上错误内容。***
答：资产编辑里面有说明，但是资产详情里没有
![DEVICE-2023129-00001-详情-☕️-CAT](https://github.com/celaraze/cat/assets/50667512/9b81d998-d14a-4f02-8714-606888af3503)

![编辑-DEVICE-2023129-00001-☕️-CAT](https://github.com/celaraze/cat/assets/50667512/aa7257a6-e97a-4f3f-a569-aeb1ecdcb89f)

**Comment by celaraze** [comment]
收到，本周例行发行版中会修复，感谢。
