### ISSUE TITLE
对资产分配用户的记录,记录操作账号

### ISSUE THREAD

**Issue by minishiguang** [celaraze/cat#114]
### 须知

1，更希望用户能提供 PR 来增加新工能，而不是在 Issue 中表述。
2，建议的新功能，也不一定开发和实装。

### 你的想法
对资产分配用户的操作,需要对操作账号进行记录
请说。
![image](https://github.com/celaraze/cat/assets/22143662/0a19a2f8-a323-42dd-9103-354378beb21b)

**Comment by celaraze** [comment]
收到，下个版本 `v1.0.4` 增加。

**Comment by celaraze** [comment]
`v1.0.4` 已增加。
