### ISSUE TITLE
角色权限”重置密码“上的策略问题

### ISSUE THREAD

**Issue by YC119** [celaraze/cat#116]
### 先确认

***1，是否使用最新版本，可以使用 `php artisan cat:version` 获取当前版本。***
答：是

***2，是否有跳过应用处理逻辑，而自行修改数据库结构、数据等操作。***
答：无

***3，是否有二次开发操作。***
答：无

### 再描述

***1，你的 PHP 、 MySQL 版本号。***
答：默认最新

***2，当前使用的 CAT 版本号。***
答：1.0.4

***3，你遇到了什么问题，尽量描述清楚，尤其是附上错误内容。***
答：请考虑在”角色“分配”用户权限“中，对授权“重置密码”的选项，进行一个调整：即被授权“重置密码”的角色不可相互之间进行”重置密码“，只能由超级管理员进行重置。因为目前是普通管理员可以重置admin的密码，这点有些奇怪

**Comment by celaraze** [comment]
好提议，我可以这么理解，拥有这个 `重置密码` 权限的角色，不能被普通用户或者其他管理员执行，仅能由超级管理员执行。

**Comment by celaraze** [comment]
已修复，`v1.0.5` 实装。
