### ISSUE TITLE
搜索内容后点击跳转问题

### ISSUE THREAD

**Issue by superx1688** [celaraze/cat#117]
### 先确认

***1，是否使用最新版本。***
答：1.0.4

***2，是否有跳过应用处理逻辑，而自行修改数据库结构、数据等操作。***
答：无

***3，是否有二次开发操作。***
答：无

### 再描述

***1，你的 PHP 、 MySQL 版本号。***
答：docker版本

***2，当前使用的 CAT 版本号。***
答：1.0.4

***3，你遇到了什么问题，尽量描述清楚，尤其是附上错误内容。***
答：在右上角搜索时，如搜索资产编号00002，出来了搜索信息，是设备，那么点击后应该是查看，而现在点击是直接编辑，查看才是正确一点

**Comment by celaraze** [comment]
收到，我确认一下。

**Comment by celaraze** [comment]
已修复，下一个版本 `v1.0.5` 发布。
