### ISSUE TITLE
拥有“用户”编辑权限的普通管理员，可自我提权至超级管理员

### ISSUE THREAD

**Issue by YC119** [celaraze/cat#118]
### 先确认

***1，是否使用最新版本。***
答：是

***2，是否有跳过应用处理逻辑，而自行修改数据库结构、数据等操作。***
答：无

***3，是否有二次开发操作。***
答：无

### 再描述

***1，你的 PHP 、 MySQL 版本号。***
答：默认最新

***2，当前使用的 CAT 版本号。***
答：1.0.5

***3，你遇到了什么问题，尽量描述清楚，尤其是附上错误内容。***
答：拥有“用户”编辑权限的普通管理员，可自我提权至超级管理员

**Comment by celaraze** [comment]
收到，下个版本修复。

**Comment by celaraze** [comment]
将于新版本 `v1.0.6` 正式版发布实装。
