### ISSUE TITLE
拥有“用户”删除权限的角色，可以删除超级管理员

### ISSUE THREAD

**Issue by YC119** [celaraze/cat#119]
### 先确认

***1，是否使用最新版本。***
答：是

***2，是否有跳过应用处理逻辑，而自行修改数据库结构、数据等操作。***
答：无

***3，是否有二次开发操作。***
答：无

### 再描述

***1，你的 PHP 、 MySQL 版本号。***
答：默认最新

***2，当前使用的 CAT 版本号。***
答：1.0.5

***3，你遇到了什么问题，尽量描述清楚，尤其是附上错误内容。***
答：拥有“用户”删除权限的角色，可以删除超级管理员。需要注意的是该项不可以单纯互相禁用删除，不然当普通管理员忘记密码时，超级管理员无法进行重置密码和删除角色就尴尬了

**Comment by celaraze** [comment]
收到，下版本修复。

**Comment by celaraze** [comment]
将于新版本 `v1.0.6` 正式版发布实装。
