### ISSUE TITLE
功能建议：用户默认头像显示为名称首字母

### ISSUE THREAD

**Issue by YC119** [celaraze/cat#120]
### 须知

1，更希望用户能提供 PR 来增加新工能，而不是在 Issue 中表述。
2，建议的新功能，也不一定开发和实装。

### 你的想法

功能建议：用户默认头像显示为名称首字母。这仅仅只是一个美化建议

1、因为我在测试时，经常切换用户，有时候会忘记现在登录在哪一个账户，需要点击头像后才能知道结果
2、揣测更多的使用者，可能不会特地上传头像，目前默认的无图头像，的确有点太过统一

**Comment by celaraze** [comment]
是个好建议，我考虑一下。

**Comment by celaraze** [comment]
将于新版本 `v1.0.6` 正式版发布实装。
