### ISSUE TITLE
新增设备名称不能为空如果空会有bug

### ISSUE THREAD

**Issue by jklist** [celaraze/cat#121]
![image](https://github.com/celaraze/cat/assets/115347699/ef1b20fc-ac01-4b24-b633-5a3bf359a434)
![a79fa45c01c726fdde3e5c6a3b68b83e](https://github.com/celaraze/cat/assets/115347699/fe02d531-c406-4170-ae33-6c1dba0fc7f1)

**Comment by celaraze** [comment]
已修复，下个版本发布。发布前临时解决办法是 `名称` 字段必填。

**Comment by celaraze** [comment]
新版本 `v1.0.6` 发布实装。
