### ISSUE TITLE
希望尽可能保留老版的"自定义字段"功能

### ISSUE THREAD

**Issue by dinghe1985** [celaraze/cat#122]
此功能可以实现很大的兼容性，是非常好的特性。

**Comment by celaraze** [comment]
自定义字段不会在开发计划中，使用自定义字段实现的管理模式只有两种情况：
1，管理混乱
2，CAT 没有管辖到某些内容

如果是 1，建议优化流程。
如果是 2，请提出具体场景和使用需求，会尽可能的覆盖使用场景。

详细原因请参考 [常见问题](https://github.com/celaraze/cat/wiki/%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98)
