### ISSUE TITLE
自定义表单相关问题

### ISSUE THREAD

**Issue by yuhongwei380** [celaraze/cat#124]
### 须知

1，更希望用户能提供 PR 来增加新工能，而不是在 Issue 中表述。
2，建议的新功能，也不一定开发和实装。

### 你的想法
请说。
1.自定义资产的表单，发现后台好像没法灵活的调整资产的表单。之前的chemex是可以后台表单修改增加自定义然后排序等功能。
2.然后录入的资产只有报废一个选择，如果是准备录入一些资产进行测试，那是否可以考虑增加删除的按钮？删除的权限掌控在管理员上。

**Comment by celaraze** [comment]
1：不支持，参考 #122
2：不会去添加为了测试录入而写大量的判断及冗余代码增加负担，需要测试请搭建测试环境，另外 `强制报废` 约等于 `直接删除` 资产。

**Comment by yuhongwei380** [comment]
OK
