### ISSUE TITLE
编辑角色的页面中，有一个用途不明的搜索框

### ISSUE THREAD

**Issue by YC119** [celaraze/cat#125]
### 先确认

***1，是否使用最新版本。***
答：时

***2，是否有跳过应用处理逻辑，而自行修改数据库结构、数据等操作。***
答：否

***3，是否有二次开发操作。***
答：否

### 再描述

***1，你的 PHP 、 MySQL 版本号。***
答：默认最新

***2，当前使用的 CAT 版本号。***
答：1.0.6.1

***3，你遇到了什么问题，尽量描述清楚，尤其是附上错误内容。***
答：编辑角色的页面中，拉到底部，有一个搜索框。这个搜索框似乎搜不到任何东西，如果是用于筛选权限的，那布局也应处于表的最上方而不是底部

**Comment by celaraze** [comment]
这是一个针对开发过程中的自定义页面权限定义，这个搜索框下面的都是自定义页面的权限，实际上这部分权限没必要细化，后续版本会移除。

**Comment by celaraze** [comment]
下个版本将移除。
