### ISSUE TITLE
组织页面中的”展开“和”折叠“按钮点不动

### ISSUE THREAD

**Issue by YC119** [celaraze/cat#127]
### 先确认

***1，是否使用最新版本。***
答：是

***2，是否有跳过应用处理逻辑，而自行修改数据库结构、数据等操作。***
答：否

***3，是否有二次开发操作。***
答：否

### 再描述

***1，你的 PHP 、 MySQL 版本号。***
答：最新

***2，当前使用的 CAT 版本号。***
答：1.0.6.1

***3，你遇到了什么问题，尽量描述清楚，尤其是附上错误内容。***
答：组织页面中的”展开“和”折叠“按钮点不动。好奇功能正常时，展开的内容是组织成员么？

**Comment by celaraze** [comment]
参考 [http://cat.celaraze.com:50080/organizations](http://cat.celaraze.com:50080/organizations) 。
展开用于多级组织。

**Comment by YC119** [comment]
原来是这样啊。依靠鼠标拖动组织的顺序，从而搭建出组织的多层架构。原先以为拖动仅仅只是排序。

**Comment by celaraze** [comment]
> 原来是这样啊。依靠鼠标拖动组织的顺序，从而搭建出组织的多层架构。原先以为拖动仅仅只是排序。

是的，组织架构框架实现了，但还没实装相关功能，后续和云集成有关联，暂时放在那。
