### ISSUE TITLE
快速预览显示信息有误

### ISSUE THREAD

**Issue by meitangdehulu** [celaraze/cat#128]
### 先确认

***1，是否使用最新版本。***
答：是的

***2，是否有跳过应用处理逻辑，而自行修改数据库结构、数据等操作。***
答：没有

***3，是否有二次开发操作。***
答：没有

### 再描述

***1，你的 PHP 、 MySQL 版本号。***
答：Docker快速安装无MYSQL，php8.3

***2，当前使用的 CAT 版本号。***
答：1.0.5

***3，你遇到了什么问题，尽量描述清楚，尤其是附上错误内容。***
答：快速预览页面的使用人显示为分派人（管理员）而非用户。
resources/views/filament/actions/devices/summary.blade.php

**Comment by celaraze** [comment]
已确认，下个版本 `v1.0.6` 修复。
