### ISSUE TITLE
资产创建中的自定义分类字段，需要提供删除能力

### ISSUE THREAD

**Issue by YC119** [celaraze/cat#129]
### 先确认

***1，是否使用最新版本。***
答：是

***2，是否有跳过应用处理逻辑，而自行修改数据库结构、数据等操作。***
答：否

***3，是否有二次开发操作。***
答：否

### 再描述

***1，你的 PHP 、 MySQL 版本号。***
答：最新

***2，当前使用的 CAT 版本号。***
答：1.0.10

***3，你遇到了什么问题，尽量描述清楚，尤其是附上错误内容。***
答：资产创建中，分类、品牌、单位等均可自行添加新的分类这很棒~但尚如果打错字点了新增，现阶段无法删除该字段。除此之外“配件”的分类中就有键鼠，和“耗材”中进行键鼠管理，也稍显人为理解上的冲突。故此需要一个删除的功能，例如谷歌浏览器上地址栏搜索结果的右侧，有个“X”这样的形式

**Comment by celaraze** [comment]
资产页面，高级按钮，分类可以管理。创建页面只是提供一个快捷创建分类的功能，用户不需要额外跳转页面去创建分类。

**Comment by YC119** [comment]
哦哦，现在注意到了。逻辑满分，当然，如果在快捷创建界面，就能集成快捷删除，那就更好了..

**Comment by YC119** [comment]
从用户操作直觉角度出发，既然我有权限可以维护（删除）错误或不需要的条目，可以不跳转就能完成删除一定更为友好。您后期有时间的时候，可以考虑以下这个细节优化

**Comment by celaraze** [comment]
这会陷入一个无尽的逻辑黑洞，会让使用者混淆当前真实的创建目的到底是在管理资产本身，还是在管理资产分类，快速创建分类本身是提升效率的入口，并不是约束使用者是否填写正确的规范。

写错、删除分类，请前往分类管理，这本应该在这里处理，并且处理过程受权限分配管理及记录日志。

**Comment by YC119** [comment]
好的，我理解并尊重您的思路
