### ISSUE TITLE
“耗材”未纳入“盘点”

### ISSUE THREAD

**Issue by YC119** [celaraze/cat#130]
### 先确认

***1，是否使用最新版本。***
答：是

***2，是否有跳过应用处理逻辑，而自行修改数据库结构、数据等操作。***
答：否

***3，是否有二次开发操作。***
答：否

### 再描述

***1，你的 PHP 、 MySQL 版本号。***
答：最新

***2，当前使用的 CAT 版本号。***
答：1.0.10

***3，你遇到了什么问题，尽量描述清楚，尤其是附上错误内容。***
答：“工作流-盘点”中，软件盘点可能不需要？当然有总比没有好，这里主要想说的是1.0.10版本新增的“耗材”，是否需要进行盘点作业的考虑？

**Comment by celaraze** [comment]
新功能未写完，beta 版本不接受功能相关 Issue，如果版本没有的功能，就是这版本不提供，注重稳定和问题修复。
