### ISSUE TITLE
宝塔安装报错

### ISSUE THREAD

**Issue by yuanf225** [celaraze/cat#131]
### 先确认

***1，是否使用最新版本。***
答：是

***2，是否有跳过应用处理逻辑，而自行修改数据库结构、数据等操作。***
答：否

***3，是否有二次开发操作。***
答：否

### 再描述

***1，你的 PHP 、 MySQL 版本号。***
答：php8.2 mysql8.0

***2，当前使用的 CAT 版本号。***
答：[ebf91d7](https://github.com/celaraze/cat/commit/ebf91d72aacabb1f3152d9a42fcc81ab9ad3e1f8)

***3，你遇到了什么问题，尽量描述清楚，尤其是附上错误内容。***
答：我在宝塔面板进行部署，参考安装教程进行，在执行php artisan cat:install时候报错

PHP Warning:  Module "ldap" is already loaded in Unknown on line 0
欢迎使用 CAT 一站式运维平台

   INFO  Clearing cached bootstrap files.  

  events ............................................................ 3ms DONE
  views ............................................................. 5ms DONE
  cache ............................................................. 1ms DONE
  route ............................................................. 1ms DONE
  config ............................................................ 1ms DONE
  compiled .......................................................... 1ms DONE

正在设置存储系统

   Error 

  Call to undefined function Illuminate\Filesystem\symlink()

  at vendor/laravel/framework/src/Illuminate/Filesystem/Filesystem.php:356
    352▕      */
    353▕     public function link($target, $link)
    354▕     {
    355▕         if (! windows_os()) {
  ➜ 356▕             return symlink($target, $link);
    357▕         }
    358▕ 
    359▕         $mode = $this->isDirectory($target) ? 'J' : 'H';
    360▕ 

      +11 vendor frames 

  12  app/Console/Commands/Install.php:18
      Illuminate\Console\Command::call()
      +12 vendor frames 

  25  artisan:35
      Illuminate\Foundation\Console\Kernel::handle()

**Comment by celaraze** [comment]
`php-fpm.ini` 以及 `php-cli.ini` 取消 `symlink` 函数的禁用。

如果没有解决，请自行联系宝塔社区或互联网确认，这不是应用的问题。
