### ISSUE TITLE
SSO/ldap功能建议

### ISSUE THREAD

**Issue by yuanf225** [celaraze/cat#132]
现在很多企业都有自己的单点登录，如果能集成一个单点登录的功能就更好了，个人建议。

**Comment by celaraze** [comment]
如果你在用户社区（QQ 频道）里，就能看到我对此的开发计划。是有的，但不是现在。
这个项目目前只有我一个人开发，时间精力有限，我已规划了这些功能，但开源项目需要我有充裕的个人时间来处理。

**Comment by yuanf225** [comment]
辛苦啦
