### ISSUE TITLE
是否可以增加资产历史流转记录

### ISSUE THREAD

**Issue by CookPumpkin** [celaraze/cat#137]
设备详情里可以增加个历史流转记录，可追溯设备分配使用情况。可以追溯设备是要哪个部门的人申请承担了费用。
<img width="757" alt="1" src="https://github.com/celaraze/cat/assets/39803976/3611a51c-b717-4ad5-8210-6719f2368614">

**Comment by celaraze** [comment]
你截图的画面中就是设备的分配记录。部门后面会有，现在还没做好组织部门功能。

**Comment by CookPumpkin** [comment]
好的，谢谢
