### ISSUE TITLE
docker-compose部署之后报错

### ISSUE THREAD

**Issue by hansonhantong** [celaraze/cat#139]
![image](https://github.com/celaraze/cat/assets/22970644/2e89215d-1d7b-4a29-b161-51d2b5f98f7a)
docker日志报错信息如图

**Comment by celaraze** [comment]
提供下更加详尽的环境参数，例如 docker 版本，以及复现步骤，单一个截图无法判断。

**Comment by celaraze** [comment]
长时间未回复，关闭。
