### ISSUE TITLE
更多操作向移动端转移

### ISSUE THREAD

**Issue by hjq2413278689** [celaraze/cat#142]
### 须知

1，更希望用户能提供 PR 来增加新工能，而不是在 Issue 中表述。
2，建议的新功能，也不一定开发和实装。

### 你的想法

平台生成二维码、勾选所选资产打印标签。手机端扫码查看资产信息的同时登陆后可以直接在手机端修改资产信息，同时能新增、转移、报废等，更多的把操作权限给到手机端吗？ 同时这个生成的二维码可设置公网地址，不受内网限制。  😄

**Comment by celaraze** [comment]
移动端的需求去移动端代码仓库提。
后续会对移动端做补充开发，但时间精力有限，具体说明可以看移动端代码仓库中的说明文件。
目前不带二维码生成功能，自己用第三方工具批量生成二维码反而更效率，自行用公网地址即可。
