### ISSUE TITLE
操作确认

### ISSUE THREAD

**Issue by shibosen** [celaraze/cat#154]
# 资产添加后只能废弃，无法删除
![image](https://github.com/celaraze/cat/assets/93109624/97462a46-2ce3-453f-bec3-69886f92f515)

# 盘点记录无法删除
![image](https://github.com/celaraze/cat/assets/93109624/a0b43e00-de71-4e15-b204-d5628587d527)

**Comment by celaraze** [comment]
设计如此，不用了、写错了就废弃，资产唯一性。
