### ISSUE TITLE
啥时候出个windows一键安装呀，比如集成个xampp

### ISSUE THREAD

**Issue by 593172440** [celaraze/cat#157]

**Comment by celaraze** [comment]
docker不够用？

**Comment by 593172440** [comment]
docker在windows中配置对于小白来说太难了，关键还都是英文。

**Comment by celaraze** [comment]
> 
> ![image](https://github.com/celaraze/cat/assets/11573521/e1366909-076c-43e8-b26d-d17faa097083)
> 看环境都弄好了，按照文档一步步来都出错。
> docker在windows中配置对于小白来说太难了，关键还都是英文。

这也不是项目的问题，看样子计算机基础知识也没有掌握熟练，为何要涉足使用这个软件，本就是需要有运维知识。

如果需要帮助可以加入交流频道询问。
