### ISSUE TITLE
npm反代后排版异常

### ISSUE THREAD

**Issue by 791009147** [celaraze/cat#159]
### 先确认

***1，是否使用最新版本。***
答：1.0.5

***2，是否有跳过应用处理逻辑，而自行修改数据库结构、数据等操作。***
答：

***3，是否有二次开发操作。***
答：无

### 再描述

***1，你的 PHP 、 MySQL 版本号。***
答：unraid docker部署

***2，当前使用的 CAT 版本号。***
答：1.0.5

***3，你遇到了什么问题，尽量描述清楚，尤其是附上错误内容。***
答：
 npm反代后有排版问题，.env 中已经改了app url   请指点下
![微信截图_20240326111806](https://github.com/celaraze/cat/assets/90306728/3a885a52-1e8c-4191-9a41-481213882f45)

**Comment by celaraze** [comment]
重复 Issue，请关注 #151
