### ISSUE TITLE
文档docker build失败

### ISSUE THREAD

**Issue by yangmengren** [celaraze/cat#160]
### 先确认

***1，是否使用最新版本。***
答：
是
***2，是否有跳过应用处理逻辑，而自行修改数据库结构、数据等操作。***
答：否

***3，是否有二次开发操作。***
答：否

### 再描述

***1，你的 PHP 、 MySQL 版本号。***
答：容器，mysql8

***2，当前使用的 CAT 版本号。***
答：最新拉取

***3，你遇到了什么问题，尽量描述清楚，尤其是附上错误内容。***
答：在docker build中，出现报错：ERROR: failed to solve: process "/bin/sh -c composer install -vvv     && if [ -f /var/www/database/data/database.sqlite ]; then rm /var/www/database/data/database.sqlite; fi     && touch /var/www/database/data/database.sqlite     && cp .env.docker .env     && php artisan cat:install" did not complete successfully: exit code: 1

**Comment by rakuten** [comment]
main里和1.0.5的Dockerfile我前天刚build过，全都是可以的

应该是你前面步骤有东西没安装成功，可能的网络问题，建议换不同时间段再多试几次

**Comment by celaraze** [comment]
composer 需要稳定的翻墙网络，如果没有就多试几次。
