### ISSUE TITLE
宝塔面板安装CAT失败

### ISSUE THREAD

**Issue by MuGongziya** [celaraze/cat#163]
### 先确认

***1，是否使用最新版本。***
答：是的

***2，是否有跳过应用处理逻辑，而自行修改数据库结构、数据等操作。***
答：没有

***3，是否有二次开发操作。***
答：没有

### 再描述

***1，你的 PHP 、 MySQL 版本号。***
答：PHP8.1.27   MYSQL8.0.36

***2，当前使用的 CAT 版本号。***
答： v1.0.3

***3，你遇到了什么问题，尽量描述清楚，尤其是附上错误内容。***
答：宝塔面板执行最后一步 php artisan cat:install  失败。提示如下，好像是没有vendor这个目录。
都是按照  [https://celaraze.com/wiki/cat.html](url) 宝塔面板教程来操作的，composer版本是2.7.4。

![c](https://github.com/celaraze/cat/assets/66168501/bd774cd2-57b0-414b-be50-c0ccbec5dd6a)
![p](https://github.com/celaraze/cat/assets/66168501/028c4049-ceda-4b94-83af-99ca2fa15271)

**Comment by MuGongziya** [comment]
这个是网页打开提示的错误
![113](https://github.com/celaraze/cat/assets/66168501/2c6c5905-6f6b-483b-b810-cd44eb072607)

**Comment by baobao323** [comment]
一样的问题

**Comment by majiameng** [comment]
> 这个是网页打开提示的错误 ![113](https://private-user-images.githubusercontent.com/66168501/326229593-2c6c5905-6f6b-483b-b810-cd44eb072607.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY3Mjg2NzIsIm5iZiI6MTcxNjcyODM3MiwicGF0aCI6Ii82NjE2ODUwMS8zMjYyMjk1OTMtMmM2YzU5MDUtNmY2Yi00ODNiLWI4MTAtY2Q0NGViMDcyNjA3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTI2VDEyNTkzMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWViNjM0OWUyYzZhMjAxMDMwMWVmMzBhYzdmM2I2OGNmMDJiOThhZThjNmEzZDdhNzU3ZjcyNjQyN2E0Y2RkYzQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.m7EUd-MKVE8kbhNTh_WySn4Ult6xOFSpqn2E7q-dLHw)

把宝塔里的：防跨站攻击(open_basedir)  关闭这个错误就没有了

**Comment by celaraze** [comment]
composer 依赖没有安装成功，缺少了 php 相关扩展，看样子是少了 php-xml 扩展。

**Comment by MuGongziya** [comment]
已经装好了&nbsp; 需要忽略版本安装



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年5月28日(周二) 中午12:12
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [celaraze/cat] 宝塔面板安装CAT失败 (Issue #163)




 
composer 依赖没有安装成功，缺少了 php 相关扩展，看样子是少了 php-xml 扩展。
